export default {
  items: [{
    id: 1,
    lastName: 'Jacques',
    firstName: 'Last',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 2,
    lastName: 'Pierre',
    firstName: 'Last',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 3,
    lastName: 'Ana',
    firstName: 'Amop',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 4,
    lastName: 'Cyril',
    firstName: 'Vimard',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 5,
    lastName: 'Jonathan',
    firstName: 'Reza',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 6,
    lastName: 'Pierre',
    firstName: 'Feuille',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 7,
    lastName: 'Octave',
    firstName: 'Jean',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 8,
    lastName: 'Cyril',
    firstName: 'Second',
    phone: '0612345678',
    city: 'marseille',
  }],
};
