export default {
  items: [{
    id: 1,
    firstName: 'Jacques',
    lastName: 'JacquesLast',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 2,
    firstName: 'Pierre',
    lastName: 'PierreLast',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 3,
    firstName: 'Jean',
    lastName: 'JeanLast',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 4,
    firstName: 'Cyril',
    lastName: 'Vimard',
    phone: '0612345678',
    city: 'paris',
  }, {
    id: 5,
    firstName: 'Jonathan',
    lastName: 'Reza',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 6,
    firstName: 'Pierre',
    lastName: 'PierreLast',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 7,
    firstName: 'Jean',
    lastName: 'JeanLast',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 8,
    firstName: 'Cyril',
    lastName: 'Vimard',
    phone: '0612345678',
    city: 'marseille',
  }, {
    id: 12,
    firstName: 'Cyril',
    lastName: 'Vimard',
    phone: '0612345678',
    city: 'londres',
  }],
};
